[package]
name = "bevy_prototype_debug_lines"
version = "0.1.3"
authors = ["Michael Palmos <toqoz@hotmail.com>"]
edition = "2018"
license = "MIT"
description = "A prototype plugin providing a simple line drawing API for bevy."
homepage = "https://github.com/Toqozz/bevy_debug_lines"
repository = "https://github.com/Toqozz/bevy_debug_lines"
keywords = ["debug", "line", "graphics", "bevy", "drawing"]
categories = ["game-engines", "rendering", "game-development"]

exclude = [
    "demo.webm",
    "demo.gif",
    "demo2.gif",
]

[dependencies]
bevy = { version = "0.4", default-features = false, features = ["render"] }

[features]
example_deps = ["bevy/bevy_wgpu", "bevy/bevy_winit", "bevy/bevy_gltf", "bevy/x11"]

[[example]]
name = "3d"
required-features = ["example_deps"]

[[example]]
name = "2d"
required-features = ["example_deps"]

[[example]]
name = "bench"
required-features = ["example_deps"]
